hello:            Hello. Please authorize me to start working.
authorized:       |
                  Now I'll remember you.
                  Use `help` to find out more about me.
stranger:         Sorry, but I don't know you. Try to readd me into your roster.
tz_set:           Timezone was set.
tz_not_set:       |
                  You havn't set timezone yet.
                  Use `help tz` to find out more about this stuff.
wrong_tz:         |
                  There is no such timezone.
                  Use `help tz` to get the full list.
wrong_date:       The datetime you have entered is WRONG (%s).
passed_date:      Sorry, I can't go back in time.
far_date:         Bots don't live so long. T_T
record_added:     I'll remember this date %s.
record_add_error: Can't remember this. And I don't really understand why. >_>
misunderstand:    |
                  Sorry, I didn't understand you. ^^"
                  Use `help` if you need.
help_en:             adsfgbd
help_tz:          asdfgsfsad
empty_message:    You told me to remind of something.
list_cleared:     Your list is empty now.
deleted:          Deleted!
