hello:            Hello. Please authorize me to start working.
authorized:       |
                  Now I'll remember you.
                  Use `help` to find out more about me.
stranger:         Sorry, but I don't know you. Try to readd me into your roster.
tz_set:           Timezone was set.
tz_not_set:       |
                  You havn't set timezone yet.
                  Use `help tz` to find out more about this stuff.
wrong_tz:         |
                  There is no such timezone.
                  Use `help tz` to get the full list.
wrong_date:       The datetime you have entered is wrong.
passed_date:      Sorry, I can't go back in time.
record_added:     I'll remember this date %s.
record_add_error: Can't remember this. And I don't really understand why. >_>
record_not_found: |
                  I have no record with such number.
                  Use `list` to show all.
record_deleted:   Forgotten!
empty_message:    You told me to remind of something.
list_cleared:     Your list is empty now.
list_empty:       You haven't any record.
help_text:        |
                  To set the time when I'll send you a message use `datetime message_text` (`message_text` is optional). To see `datetime` format use `help format`.
                  To see records list use `list`.
                  To delete record use `del record_number`. To delete all records `del *`
                  To set timezone use `tz timezone_name`. To see available timezones use `help tz`. Current timezone `tz`
help_format:      |
                  Date format
                  2d: 2 days
                  2w: 14 days
                  3w d: 22 days
                  08-11, 8-11, 11.08, 11.8: 11 August
                  2012-08-11, 12-08-11, 11.08.12, 11.8.2012: 11 August 2012
                  Time format
                  5m: 5minutes
                  2h: 2 hour 
                  1h 5m: 1 hour 5 minutes
                  10 a.m., 10 am: 10:00 a.m.
                  10:15 p.m., 10:15 pm: 10:15 p.m.
                  06:05, 6:5: 06:05
                  Examples
                  h message: send a message after an hour (you can ommit 1 for all options)
                  10:00 message: if it's already 15:00 (for example), I'll send a message tomorrow at 10:00, otherwise today at 10:00
                  5m message: send a message after 5 minutes
                  2d 12h message: send a message after 2.5 days
                  w 10:15 pm message: send a message after 7 days at 10:15 p.m.
misunderstand:    |
                  Sorry, I didn't understand you. ^^"
                  Use `help` if you need.
